Automação de captura da plataforma ONS c

In [178]:
import os
import time
import urllib.request
import telegram
from datetime import datetime, timedelta
import pandas as pd

# Define o número de dias anteriores para buscar as URLs das regiões
num_days = 4

# Obtém as datas dos últimos 'num_days' dias e inverte a lista para buscar da menor para a maior data
dates = [datetime.today() - timedelta(days=x) for x in range(num_days)][::-1]

# Define os formatos das datas para uso na URL e no nome do arquivo
date_formats = [date.strftime('%Y_%m_%d') for date in dates]
date_formats2 = [date.strftime('%d-%m-%Y') for date in dates]

# Define as URLs para cada região e para cada data (BALANÇO DE ENERGIA ACUMULADA DIÁRIA - BEA)
url_regioes = {}
for i in range(num_days):
    url_regioes[date_formats[i]] = {
        'sul': f'https://sdro.ons.org.br/SDRO/DIARIO/{date_formats[i]}/HTML/03_DadosDiariosAcumulados_Regiao_{date_formats2[i]}.xlsx',
        'sudeste': f'https://sdro.ons.org.br/SDRO/DIARIO/{date_formats[i]}/HTML/04_DadosDiariosAcumulados_Regiao_{date_formats2[i]}.xlsx',
        'nordeste': f'https://sdro.ons.org.br/SDRO/DIARIO/{date_formats[i]}/HTML/05_DadosDiariosAcumulados_Regiao_{date_formats2[i]}.xlsx',
        'norte': f'https://sdro.ons.org.br/SDRO/DIARIO/{date_formats[i]}/HTML/06_DadosDiariosAcumulados_Regiao_{date_formats2[i]}.xlsx'
    }

# Percorre as URLs das regiões para tentar baixar os arquivos
for data, urls in url_regioes.items():
    for regiao, url in urls.items():
        filename = f'BEA_D_{regiao.upper()}_{data}.xlsx'
        try:
            urllib.request.urlretrieve(url, filename)
            bot = telegram.Bot(token='SEU_TOKEN_AQUI')
            bot.send_message(chat_id='SEU_CHAT_ID_AQUI', text=f'Arquivo de {regiao} da data {data} baixado com sucesso')
        except urllib.error.HTTPError:
            bot = telegram.Bot(token='SEU_TOKEN_AQUI')
            bot.send_message(chat_id='SEU_CHAT_ID_AQUI', text=f'Arquivo de {regiao} da data {data} não encontrado')
            continue

C:\Users\ghumb\AppData\Local\Temp\ipykernel_2192\1021835790.py:35: RuntimeWarning: coroutine 'Bot.send_message' was never awaited
  bot.send_message(chat_id='SEU_CHAT_ID_AQUI', text=f'Arquivo de {regiao} da data {data} baixado com sucesso')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\ghumb\AppData\Local\Temp\ipykernel_2192\1021835790.py:38: RuntimeWarning: coroutine 'Bot.send_message' was never awaited
  bot.send_message(chat_id='SEU_CHAT_ID_AQUI', text=f'Arquivo de {regiao} da data {data} não encontrado')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

In [191]:
import numpy as np

dfs = []
for date in date_formats:
    df_date = pd.DataFrame()
    for regiao in ['sul','sudeste', 'nordeste', 'norte']:
        filename = f'BEA_D_{regiao.upper()}_{date}.xlsx'
        if os.path.exists(filename):
            df = pd.read_excel(filename, sheet_name='Plan1')
            df['data_captura'] = date
            df['regiao'] = regiao
            df_date = pd.concat([df_date, df], axis=0)
        dfs.append(df_date)

# Concatena e remove col completamente vazias
df_BEA_D = pd.concat(dfs, axis=0).dropna()

# Renomeia colunas
df_BEA_D = df_BEA_D.rename(columns={'Unnamed: 0': 'data',
                         'Unnamed: 1': 'total',
                         'Unnamed: 2': 'hidraulica',
                         'Unnamed: 3': 'termica',
                         'Unnamed: 4': 'eolica',
                         'Unnamed: 5': 'solar',
                         'Unnamed: 6': 'intercambio',
                         'Unnamed: 7': 'carga'})

# Limpando o dataframe
to_remove = ['Dados Diários acumulados', 'Valores - MWmed', 'Subsistema Norte', 'Total', np.nan,'Data', 'Subsistema Sul', 'Subsistema Nordeste', 'Subsistema Sudeste']
df_BEA_D = df_BEA_D[~df_BEA_D['data'].isin(to_remove)]

# Remove valores que se repetem em 'data' e 'regiao', incluindo valores vazios
df_BEA_D.drop_duplicates(subset=['data', 'regiao'], inplace=True)

#atualizando formato dos dados
df_BEA_D['total'] = pd.to_numeric(df_BEA_D['total'], errors='coerce')
df_BEA_D['hidraulica'] = pd.to_numeric(df_BEA_D['hidraulica'], errors='coerce')
df_BEA_D['termica'] = pd.to_numeric(df_BEA_D['termica'], errors='coerce')
df_BEA_D['eolica'] = pd.to_numeric(df_BEA_D['eolica'], errors='coerce')
df_BEA_D['solar'] = pd.to_numeric(df_BEA_D['solar'], errors='coerce')
df_BEA_D['intercambio'] = pd.to_numeric(df_BEA_D['intercambio'], errors='coerce')
df_BEA_D['carga'] = pd.to_numeric(df_BEA_D['carga'], errors='coerce')
df_BEA_D['data'] = pd.to_datetime(df_BEA_D['data'], format='%d/%m/%Y')
df_BEA_D['data_captura'] = pd.to_datetime(df_BEA_D['data_captura'], format='%Y_%m_%d')

df_BEA_D

,data,total,hidraulica,termica,eolica,solar,intercambio,carga,data_captura,regiao
7,2023-03-01,9615.22,8135.15,775.88,702.35,1.83,-3914.06,13529.27,2023-03-04,sul
8,2023-03-02,10569.61,9334.27,845.57,388.60,1.17,-3747.37,14316.98,2023-03-04,sul
9,2023-03-03,10792.39,9708.28,700.89,382.06,1.17,-3398.78,14191.17,2023-03-04,sul
10,2023-03-04,9407.62,8252.39,742.70,411.36,1.17,-2407.85,11815.47,2023-03-04,sul
7,2023-03-01,40446.92,35956.06,3715.16,5.98,769.72,-3911.96,44358.88,2023-03-04,sudeste
8,2023-03-02,39800.24,35331.19,3596.97,11.58,860.50,-5236.76,45037.00,2023-03-04,sudeste
9,2023-03-03,40949.15,36325.95,3716.76,11.58,894.87,-4861.34,45810.49,2023-03-04,sudeste
10,2023-03-04,36627.35,32048.43,3672.33,11.62,894.96,-5592.81,42220.16,2023-03-04,sudeste
7,2023-03-01,16622.03,3543.43,495.25,11333.51,1249.84,4266.37,12355.66,2023-03-04,nordeste
8,2023-03-02,16152.01,3490.33,450.08,11242.87,968.73,4230.11,11921.90,2023-03-04,nordeste
9,2023-03-03,14771.84,3680.01,471.19,9629.88,990.75,2873.07,11898.77,2023-03-04,nordeste
10,2023-03-04,14494.39,3508.41,461.70,9734.71,789.57,3150.15,11344.24,2023-03-04,nordeste
7,2023-03-01,11946.32,10594.25,1063.38,287.29,1.40,5125.81,6820.51,2023-03-04,norte
8,2023-03-02,13390.60,12031.80,1173.65,184.11,1.04,6501.25,6889.35,2023-03-04,norte
9,2023-03-03,13972.73,12858.04,975.25,138.40,1.04,7095.12,6877.61,2023-03-04,norte
10,2023-03-04,13236.88,12347.12,763.56,125.15,1.04,6724.64,6512.25,2023-03-04,norte
11,2023-03-05,8120.23,6597.63,1060.87,460.56,1.17,-1895.01,10015.24,2023-03-05,sul
11,2023-03-05,32416.63,27922.40,3651.21,11.58,831.44,-6088.40,38505.03,2023-03-05,sudeste
11,2023-03-05,13793.69,3397.54,457.74,9039.14,899.26,3249.83,10543.87,2023-03-05,nordeste
11,2023-03-05,12564.20,11511.42,834.28,217.42,1.08,6260.37,6303.83,2023-03-05,norte

data            datetime64[ns]
total                  float64
hidraulica             float64
termica                float64
eolica                 float64
solar                  float64
intercambio            float64
carga                  float64
data_captura    datetime64[ns]
regiao                  object
dtype: object